mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.weirdstudio.model

spring:
  datasource:
    url: jdbc:mysql://94.191.65.57:3306/xcode?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: xcode
    password: qTNG4Kis7yezXL4fYcPirjWX/fxoAg0f0DRkcNnmFp7fNfh93Iq/eFjUbgvrq/jCIyHrMkoBoqb7T++e7SGe1A==
#    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${public-key}
      use-global-data-source-stat: true
      filter:
        config:
          enabled: true
        stat:
          enabled: true
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        reset-enable: false

thymeleaf:
  cache: false

publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK2A10fnTb0B6K4BkEwPg8VXxgyW77WIVnmu7O5550zpgnAICSWFlkBd0aX6m52Vt345D8ihoRyZy1ZKuLfc9EkCAwEAAQ==